### ISSUE TITLE
Continue to support python 3.9 

### ISSUE THREAD

**Issue by ebrahimebrahim** [OpenwaterHealth/OpenLIFU-python#167]
k-wave-python [dropped python 3.9 support](https://github.com/waltsims/k-wave-python/pull/505) in [the latest release](https://github.com/waltsims/k-wave-python/releases/tag/v0.3.6)

We may have to pin the k-wave-python version or maintain a parallel fork, because OpenLIFU-python needs to support python3.9 in order to be used in 3D Slicer.

**Comment by arhowe00** [comment]
We should pin the version of kwave to 0.3.4. k-wave-python 0.3.5 is automatically installed as a dependency, which introduces the following bug:

```
Traceback (most recent call last):
  File "./SlicerOpenLIFU-Debug/lib/Slicer-5.7/qt-scripted-modules/OpenLIFUSonicationPlanner.py", line 300, in onComputeSolutionClicked
    self.logic.computeSolution(activeData["Volume"], activeData["Target"],
  File "./SlicerOpenLIFU-Debug/lib/Slicer-5.7/qt-scripted-modules/OpenLIFUSonicationPlanner.py", line 519, in computeSolution
    solution_openlifu, pnp_aggregated, intensity_aggregated, analysis_openlifu = compute_solution_openlifu(
  File "./SlicerOpenLIFU-Debug/lib/Slicer-5.7/qt-scripted-modules/OpenLIFUSonicationPlanner.py", line 479, in compute_solution_openlifu
    solution, simulation_result_aggregated, scaled_solution_analysis = protocol.calc_solution(
  File "./Slicer-Debug/python-install/lib/python3.9/site-packages/openlifu/plan/protocol.py", line 233, in calc_solution
    simulation_output_xarray, _ = run_simulation(
  File "./Slicer-Debug/python-install/lib/python3.9/site-packages/openlifu/sim/kwave_if.py", line 115, in run_simulation
    p_max = xa.DataArray(output['p_max'].reshape(sz, order='F'),
KeyError: 'p_max'
```

The aforementioned bug was already fixed in the following commit released in k-wave-python:
```
commit 0ab1e87a4bebbe5042c476c67bb0a8f08f936d3c
Author: brubbel <5667690+brubbel@users.noreply.github.com>
Date:   Tue Nov 19 20:12:48 2024 +0100

    bugfix simulation command options (#509)

    fixes https://github.com/waltsims/k-wave-python/issues/376
```

but this was released with a version that also does not Python 3.9.
